version: "3"

services:
  mozmap:
    build: .
    image: mozmap
    restart: unless-stopped
    volumes:
     - ./data:/usr/src/app/data
    environment:
      DNSMASQ_VERBOSE: 'true'
#    expose:
#     - 3000
#     - 3443
    ports:
     - "3000:3000"
     - "3443:3443"
